# Generated by Django 4.2.1 on 2023-06-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
    ]
